//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 传智Studio.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class 传智StudioEntities2 : DbContext
    {
        public 传智StudioEntities2()
            : base("name=传智StudioEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bulletin> Bulletin { get; set; }
        public DbSet<Project> Project { get; set; }
        public DbSet<Recruit> Recruit { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Vote> Vote { get; set; }
    }
}
