//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 传智Studio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public string UserAccount { get; set; }
        public string UserPwd { get; set; }
        public string PhoneNumber { get; set; }
        public string UserName { get; set; }
        public string Sex { get; set; }
        public string Professional { get; set; }
        public string Grade { get; set; }
        public string Department { get; set; }
        public string Campus { get; set; }
        public System.DateTime RegTime { get; set; }
    }
}
